version: "3"

services:
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "6543:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
    postgres_data:
