version: "3"

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
