name: On-commit

on:
  push:
    branches:
      - feat/chore-update-status
jobs:
  build:
    runs-on: ubuntu-latest
    name: Commit status
    if: "!startsWith(github.event.head_commit.message, 'chore')"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Running builder.py
        run: python ./src/builder.py
      - name: Checkout
        uses: actions/checkout@v2 
        with:
          repository: antonkurenkov/systembuilder
          token: ${{ secrets.DEV_BOT_TOKEN }}
      - name: chore update status
        run: |
          git config --local user.email "aka1306@gmail.com"
          git config --local user.name "dev-bot0"
          git add status.json 
          git commit -am 'chore: update status'