name: scheduler
on:
  schedule:
    - cron: '*/10 * * * *'
      
jobs:
  schedule_action:
    runs-on: ubuntu-latest
    steps:
      - name: Print python version
        run: python --version
        
